#:kivy 1.0.9

<Arena>:
    size: 500, 400
    canvas:
        Color:
            rgb: 0.1, 0.1, 0.1
        Rectangle:
            pos: self.pos
            size: self.width + 10, self.height + 10

<Indicator>:
    canvas:
        Color:
            rgb: self.color
        Ellipse:
            pos: self.pos
            size: 10, 10


<PongGame>:
    arena: arena_1

    Arena:
        id: arena_1
